// Tweets mutation types
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS'
export const FETCH_TWEETS_FAILED = 'FETCH_TWEETS_FAILED'
export const FETCH_TWEETS_PENDING = 'FETCH_TWEETS_PENDING'

export const FETCH_TWEETS_BY_USER_PENDING = 'FETCH_TWEETS_BY_USER_PENDING'
export const FETCH_TWEETS_BY_USER_SUCCESS = 'FETCH_TWEETS_BY_USER_SUCCESS'
export const FETCH_TWEETS_BY_USER_FAILED = 'FETCH_TWEETS_BY_USER_FAILED'

export const FIND_TWEET_SUCCESS = 'FIND_TWEET_SUCCESS'
export const FIND_TWEET_FAILED = 'FIND_TWEET_FAILED'
export const FIND_TWEET_PENDING = 'FIND_TWEET_PENDING'

export const SAVE_TWEET_SUCCESS = 'SAVE_TWEET_SUCCESS'
export const SAVE_TWEET_FAILED = 'SAVE_TWEET_FAILED'
export const SAVE_TWEET_PENDING = 'SAVE_TWEET_PENDING'

export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS'
export const DELETE_TWEET_FAILED = 'DELETE_TWEET_FAILED'
export const DELETE_TWEET_PENDING = 'DELETE_TWEET_PENDING'

export const DELETE_TWEETS_FROM_USER_SUCCESS = 'DELETE_TWEETS_FROM_USER_SUCCESS'
export const DELETE_TWEETS_FROM_USER_FAILED = 'DELETE_TWEETS_FROM_USER_FAILED'
export const DELETE_TWEETS_FROM_USER_PENDING = 'DELETE_TWEETS_FROM_USER_PENDING'

// Users mutation types
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'
export const FETCH_USER_PENDING = 'FETCH_USER_PENDING'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING'

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING'

export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS'
export const SAVE_USER_FAILED = 'SAVE_USER_FAILED'
export const SAVE_USER_PENDING = 'SAVE_USER_PENDING'

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED'
